# Use the README file as a reference to customize settings.

Category:
  fields:
    default: name, parent_id
    form: name, parent_id
  relationships: children, victories
  application: Application
